site_name: YAP Prolog Reference Manual
site_url: https://www.dcc.fc.up.pt/YAP
use_directory_urls: false
theme:
  name: 'readthedocs'
  highlightjs: true
  hljs_languages:
    - prolog
  logo: 'images/favicon.ico'
plugins:
  - search
  - mkdoxy:
      projects:
        YAP: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: ../yapdocs
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)

            RECURSIVE: True # recursive search in source directories
            ALLOW_UNICODE_NAMES: True
            INLINE_SIMPLE_STRUCTS: True
            INLINE_GROUPED_CLASSES: True
markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - toc:
      permalink: true
nav:
   - Home: YAP/index.md
   - INSTALL: YAP/INSTALL.md
   - Calling YAP: YAP/CALLING_YAP.md
   - Core Built-ins: YAP/group__Builtins.md
   - Programming: YAP/group__YAPProgramming.md
   - Extensions: YAP/group__YapExtensions.md
   - Library: YAP/group__YAPLibrary.md
   - Available Packages: YAP/group__YAPPackages.md
   - Foreign Language Interface : YAP/group__YAPAPI.md


