site_name: YAP Prolog Reference Manual
site_url: https://www.dcc.fc.up.pt/YAP
use_directory_urls: false
theme:
  name: 'readthedocs'
  highlightjs: true
  hljs_languages:
    - prolog
  logo: 'YAP/img/favicon.ico'
plugins:
  - search
  - mkdoxy:
      projects:
        YAP: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs:      ../../C    ../../H    ../../include   ../../pl    ../../library   ../../os    ../../OPTYap    ../../packages ../../CXX  ../../docs/md
          full-doc: True # if you want to generate full documentation
          doxy-cfg-file: ../Doxyfile.dox
             # RECURSIVE: True # search in source doxx directoriesmarkdown_extensions:
nav:
   - Home: YAP/index.md
   - INSTALL: YAP/INSTALL.md
   - Calling YAP: YAP/CALLING_YAP.md
   -   Built-ins:
       - Core: YAP/group__Builtins.md
       - Input-Output: YAP/group__InputOutput.md
   - Programming: YAP/group__YAPProgramming.md
   - Extensions: YAP/group__YapExtensions.md
   - Library: YAP/group__YAPLibrary.md
   - Available Packages: YAP/group__YAPPackages.md
   - Foreign Language Interface : YAP/group__YAPAPI.md
   - Indices:
       - YAP/predicates.md
       - YAP/modules.md
       - YAP/namespaces.md
       - YAP/links.md
       - Implementation:
           - YAP/classes.md
           - YAP/files.md
